package com.tonyk.forcefield.model;

import com.tonyk.forcefield.util.Cuboid;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;

/**
 * A named force field zone: either a cuboid region, or one-or-more spherical
 * "bubble" shells generated by Force Field Beacons. Also stores the zone's
 * "shields down" baseline block state, its current enabled (raised) flag,
 * and an optional redstone block that controls it automatically.
 */
public final class ForceFieldZone {

    /**
     * One beacon's own bubble within a (possibly merged) spherical zone. A
     * freshly-placed beacon creates a zone with exactly one of these; placing
     * a second beacon inside the first bubble adds a second component to the
     * same zone instead of creating a separate zone, merging the two shapes
     * (see FieldManager#addBeaconToZone / SphereGeometry#combinedShellWorldPoints,
     * which drops any shell voxel of one component that falls inside another
     * - the "wall" between overlapping bubbles).
     */
    public static final class SphereComponent {
        private final UUID id;
        private final int x;
        private final int y;
        private final int z;
        private int radius;
        private boolean enabled;

        public SphereComponent(UUID id, int x, int y, int z, int radius, boolean enabled) {
            this.id = id;
            this.x = x;
            this.y = y;
            this.z = z;
            this.radius = radius;
            this.enabled = enabled;
        }

        public UUID getId() {
            return id;
        }

        public int getX() {
            return x;
        }

        public int getY() {
            return y;
        }

        public int getZ() {
            return z;
        }

        public int getRadius() {
            return radius;
        }

        void setRadius(int radius) {
            this.radius = radius;
        }

        /** Whether this specific beacon's own bubble is currently raised - independent of every other component in the same (possibly merged) zone. */
        public boolean isEnabled() {
            return enabled;
        }

        void setEnabled(boolean enabled) {
            this.enabled = enabled;
        }
    }

    // Stable identity that never changes, even across renames - this is what
    // physical lecterns are linked to (not the name), so renaming a field
    // never breaks an already-placed lectern.
    private final UUID id;

    private String name;
    private final FieldShape shape;
    private Cuboid cuboid;
    private int radius;
    private boolean enabled;

    // Only populated for SPHERE zones - one entry per beacon that makes up
    // this (possibly merged) bubble. Empty for CUBOID zones.
    private final List<SphereComponent> sphereComponents = new ArrayList<>();

    // Block key (see #key) -> block data string, captured at creation time
    // (or re-captured whenever the shape changes, e.g. a merge or resize).
    // This is the state blocks are restored to when the field is lowered.
    // For CUBOID zones keys are relative to the cuboid's min corner; for
    // SPHERE zones keys are absolute world coordinates (since a merged
    // zone's shape has no single center to be relative to).
    private final Map<String, String> baseline;

    private String redstoneWorld;
    private Integer redstoneX;
    private Integer redstoneY;
    private Integer redstoneZ;

    private UUID ownerUuid;
    private String ownerName;

    // Whether anyone (not just the owner/an admin) can toggle this field via
    // one of its physical lecterns. Defaults to false (private) - the owner
    // has to deliberately open it up.
    private boolean publicAccess;

    public ForceFieldZone(UUID id, String name, Cuboid cuboid, boolean enabled, Map<String, String> baseline) {
        this(id, name, FieldShape.CUBOID, cuboid, 0, enabled, baseline);
    }

    /**
     * Full constructor - used for CUBOID zones (radius is unused/0). SPHERE
     * zones are built with {@link #ForceFieldZone(UUID, String, String, boolean, Map)}
     * instead, then populated via {@link #addSphereComponent}.
     */
    public ForceFieldZone(UUID id, String name, FieldShape shape, Cuboid cuboid, int radius,
                           boolean enabled, Map<String, String> baseline) {
        this.id = id;
        this.name = name;
        this.shape = shape;
        this.cuboid = cuboid;
        this.radius = radius;
        this.enabled = enabled;
        this.baseline = new LinkedHashMap<>(baseline);
    }

    /**
     * Constructor for SPHERE zones. Starts with no components at all - the
     * caller must add at least one via {@link #addSphereComponent} right
     * after construction, which also computes the zone's bounding cuboid for
     * the first time.
     */
    public ForceFieldZone(UUID id, String name, String world, boolean enabled, Map<String, String> baseline) {
        this.id = id;
        this.name = name;
        this.shape = FieldShape.SPHERE;
        this.cuboid = new Cuboid(world, 0, 0, 0, 0, 0, 0);
        this.radius = 0;
        this.enabled = enabled;
        this.baseline = new LinkedHashMap<>(baseline);
    }

    public UUID getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    /** Prefer FieldManager#renameZone, which keeps the manager's name-to-zone map key in sync with this. */
    public void setName(String name) {
        this.name = name;
    }

    public FieldShape getShape() {
        return shape;
    }

    public boolean isSpherical() {
        return shape == FieldShape.SPHERE;
    }

    public Cuboid getCuboid() {
        return cuboid;
    }

    /**
     * Only meaningful for SPHERE zones. Adds a new beacon component (a fresh
     * bubble, or one being merged into an existing multi-beacon zone) and
     * recomputes the zone's bounding cuboid to cover every component.
     */
    public void addSphereComponent(SphereComponent component) {
        sphereComponents.add(component);
        recomputeSphereBounds();
    }

    /** Removes one beacon's component (e.g. its Delete button was used). Returns false if it wasn't part of this zone. */
    public boolean removeSphereComponent(UUID componentId) {
        boolean removed = sphereComponents.removeIf(c -> c.getId().equals(componentId));
        if (removed) {
            recomputeSphereBounds();
        }
        return removed;
    }

    /** Changes one component's radius in place and recomputes the zone's bounding cuboid. */
    public void resizeSphereComponent(SphereComponent component, int newRadius) {
        component.setRadius(newRadius);
        recomputeSphereBounds();
    }

    /** Flips one component's own raised/lowered state, independent of every other component in this zone. */
    public void setComponentEnabled(SphereComponent component, boolean enabled) {
        component.setEnabled(enabled);
    }

    public List<SphereComponent> getSphereComponents() {
        return sphereComponents;
    }

    /** Finds the component whose beacon sits at exactly this block location, if any. */
    public SphereComponent findComponentAt(int x, int y, int z) {
        for (SphereComponent c : sphereComponents) {
            if (c.getX() == x && c.getY() == y && c.getZ() == z) {
                return c;
            }
        }
        return null;
    }

    private void recomputeSphereBounds() {
        if (sphereComponents.isEmpty()) {
            return;
        }
        int minX = Integer.MAX_VALUE, minY = Integer.MAX_VALUE, minZ = Integer.MAX_VALUE;
        int maxX = Integer.MIN_VALUE, maxY = Integer.MIN_VALUE, maxZ = Integer.MIN_VALUE;
        for (SphereComponent c : sphereComponents) {
            minX = Math.min(minX, c.getX() - c.getRadius());
            minY = Math.min(minY, c.getY() - c.getRadius());
            minZ = Math.min(minZ, c.getZ() - c.getRadius());
            maxX = Math.max(maxX, c.getX() + c.getRadius());
            maxY = Math.max(maxY, c.getY() + c.getRadius());
            maxZ = Math.max(maxZ, c.getZ() + c.getRadius());
        }
        this.cuboid = new Cuboid(cuboid.getWorldName(), minX, minY, minZ, maxX, maxY, maxZ);
    }

    /**
     * Only meaningful for SPHERE zones - the first (or only) component's
     * shell radius in blocks. Kept for callers that only care about a
     * single-beacon bubble; merged zones should use {@link #getSphereComponents()}.
     */
    public int getRadius() {
        return sphereComponents.isEmpty() ? radius : sphereComponents.get(0).getRadius();
    }

    /** First component's center X. See {@link #getRadius()}'s note about merged zones. */
    public int getCenterX() {
        return sphereComponents.isEmpty() ? cuboid.getMinX() + radius : sphereComponents.get(0).getX();
    }

    /** First component's center Y. See {@link #getRadius()}'s note about merged zones. */
    public int getCenterY() {
        return sphereComponents.isEmpty() ? cuboid.getMinY() + radius : sphereComponents.get(0).getY();
    }

    /** First component's center Z. See {@link #getRadius()}'s note about merged zones. */
    public int getCenterZ() {
        return sphereComponents.isEmpty() ? cuboid.getMinZ() + radius : sphereComponents.get(0).getZ();
    }

    public boolean isEnabled() {
        return enabled;
    }

    public void setEnabled(boolean enabled) {
        this.enabled = enabled;
    }

    public Map<String, String> getBaseline() {
        return baseline;
    }

    public boolean hasRedstoneLink() {
        return redstoneWorld != null && redstoneX != null && redstoneY != null && redstoneZ != null;
    }

    public String getRedstoneWorld() {
        return redstoneWorld;
    }

    public Integer getRedstoneX() {
        return redstoneX;
    }

    public Integer getRedstoneY() {
        return redstoneY;
    }

    public Integer getRedstoneZ() {
        return redstoneZ;
    }

    public void setRedstoneLink(String world, int x, int y, int z) {
        this.redstoneWorld = world;
        this.redstoneX = x;
        this.redstoneY = y;
        this.redstoneZ = z;
    }

    public void clearRedstoneLink() {
        this.redstoneWorld = null;
        this.redstoneX = null;
        this.redstoneY = null;
        this.redstoneZ = null;
    }

    public static String key(int x, int y, int z) {
        return x + "," + y + "," + z;
    }

    public void setOwner(UUID uuid, String name) {
        this.ownerUuid = uuid;
        this.ownerName = name;
    }

    public UUID getOwnerUuid() {
        return ownerUuid;
    }

    public String getOwnerName() {
        return ownerName;
    }

    public boolean isOwnedBy(UUID uuid) {
        return ownerUuid != null && uuid != null && ownerUuid.equals(uuid);
    }

    public boolean isPublic() {
        return publicAccess;
    }

    public void setPublic(boolean publicAccess) {
        this.publicAccess = publicAccess;
    }
}
